# whitelist関係
whitelist:
  # ホワイトリストを有効にするかどうか
  isEnable: false
  # プレイヤーがホワイトリストに入る経過日数
  minDays: 10

# webhook関係
webhook:
  # OCNotifierのURL
  url: https://discord.com/api/webhooks/Example
  # SPNotifierのURL
  url2: https://discord.com/api/webhooks/Example
